// apps/vue-app/src/pages/Login.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Authentication } from "./../../../../packages/core/domain/usecases";

const props = defineProps<{
  authentication: Authentication;
}>();

const email = ref("");
const password = ref("");
const isLoading = ref(false);

const handleSubmit = async (event: Event) => {
  event.preventDefault();
  isLoading.value = true;

  try {
    await props.authentication.auth({
      email: email.value,
      password: password.value,
    });

    alert("Login realizado com sucesso!");
  } catch (error) {
    alert("Erro ao autenticar. Verifique seus dados.");
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <div class="container">
    <form @submit="handleSubmit" class="form">
      <h2>Login Vue</h2>

      <input
        type="email"
        placeholder="E-mail"
        v-model="email"
        class="input"
        required
      />

      <input
        type="password"
        placeholder="Senha"
        v-model="password"
        class="input"
        required
      />

      <button type="submit" :disabled="isLoading" class="button">
        {{ isLoading ? "Carregando..." : "Entrar" }}
      </button>
    </form>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
.form {
  display: flex;
  flex-direction: column;
  width: 300px;
  gap: 10px;
}
.input {
  padding: 10px;
  border-radius: 4px;
  border: 1px solid #ccc;
}
.button {
  padding: 10px;
  background-color: #007bff;
  color: white;
  border: none;
  cursor: pointer;
}
.button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>

// apps/react-app/src/pages/Login.tsx
import React, { useState } from "react";
import type { Authentication } from "./../../../../packages/core/domain/usecases";

type LoginProps = {
  authentication: Authentication;
};

export function Login({ authentication }: LoginProps) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setIsLoading(true);

    try {
      // Assumindo que o método auth recebe as credenciais
      await authentication.auth({ email, password });
      alert("Login realizado com sucesso!");
    } catch (error) {
      alert("Erro ao autenticar. Verifique seus dados.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      <form onSubmit={handleSubmit} style={styles.form}>
        <h2>Login React</h2>

        <input
          type="email"
          placeholder="E-mail"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          style={styles.input}
          required
        />

        <input
          type="password"
          placeholder="Senha"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          style={styles.input}
          required
        />

        <button type="submit" disabled={isLoading} style={styles.button}>
          {isLoading ? "Carregando..." : "Entrar"}
        </button>
      </form>
    </div>
  );
}

// Estilos básicos apenas para visualização
const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
  },
  form: {
    display: "flex",
    flexDirection: "column" as const,
    width: "300px",
    gap: "10px",
  },
  input: { padding: "10px", borderRadius: "4px", border: "1px solid #ccc" },
  button: {
    padding: "10px",
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    cursor: "pointer",
  },
};
